### PR TITLE
adds possibility to load bundles from external jar files

### PR DESCRIPTION
**Pull request by sidorovis**

### CODE REVIEW

**Comment by bgrozev** [comment]
@paweldomas @lyubomir Perhaps one of you guys can take a look at this one, since you're more familiar with OSGi? The context here is that Ivan is trying to make it possible to use a vanilla package of jitsi-videobridge but also include custom bundles from a jar file (see [jicoco#30](https://github.com/jitsi/jicoco/pull/30))

**Comment by ibauersachs** [comment]
ClassLoader.getSystemClassLoader() won‘t work on Java 9+ anymore.

I have a more general question though: why are we messing around with a custom, half baked OSGi implementation? There‘s at least three proper frameworks out there (Felix, Equinox, Knopflerfish) that do this already.

(And there‘s a code style mistake too, braces on same line.)

**Comment by sidorovis** [comment]
Fixed codestyle issue.

About ClassLoader.getSystemClassLoader() deprecation, I'm not Java expert, but https://docs.oracle.com/javase/9/docs/api/java/lang/ClassLoader.html#getSystemClassLoader--
has nothing about deprecation of that method and https://docs.oracle.com/javase/9/docs/api/deprecated-list.html also does not mention that.
Maybe you can help with the link or advise how to fix this ClassLoader.getSystemClassLoader() issue?

**Comment by ibauersachs** [comment]
The system classloader is not deprecated, but it isn‘t the root of the classloader chain anymore IIRC, it’s getPlatformClassloader() now.

Can you take a look at the last commit in jitsi/jitsi? There‘s the patch I used for Felix before they fixed it in the main repo.

But maybe this isn‘t an issue for this quirky implementation since the classloaders aren‘t properly separated per bundle anyway.
Which brings me back to the question: WHY??

**Comment by sidorovis** [comment]
Should I add this (I believe strange) try-catch for the JDK9 and getPlatformClassloader() ?
Or I can totally delete ClassLoader.getSystemClassLoader() and in case when JarClassLoader is unable to find necessary class by name we will call Class.forName(...) method as it was before my changes.

**Comment by damencho** [comment]
To try answering, let's say historical reasons. This project was created when we needed osgi implementation to run on android phone. When it was created felix was not working or it was loading for minutes on the mobile.
Then as this implementation is good enough to run on a phone, and quick enough on startup and as we do not use most of the osgi stuff it was good enough for jvb and then and for jicofo. 
Changing it?, not sure it is worth it the effort, but this is my opinion.

**Comment by sidorovis** [comment]
fixed test (get rid of getSystemCallLoader()) and used
+try
+        {
+            Method getPlatformClassLoader = ClassLoader.class.getMethod("getPlatformClassLoader");
+            cl = (ClassLoader) getPlatformClassLoader.invoke(null);
+        }
+        catch (NoSuchMethodException | IllegalAccessException | InvocationTargetException t)
...
instead of

**Comment by sidorovis** [comment]
@ibauersachs test was fixed (there is no getSystemCallLoader() anymore)

**Pull request merged**
